In [1]:
# Social_Network_Ads.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
df
# for windows with whole path
# df = pd.read_csv(r'/home/aditya/Interns_2026/daily_codes/week6/Social_Network_Ads.csv')

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [4]:
df.shape

(400, 5)

In [5]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [6]:
newdf = df.copy()

In [8]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [9]:
# import the label encoder class
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder() # creating the class

In [11]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [13]:
le.classes_

AttributeError: 'LabelEncoder' object has no attribute 'classes_'

In [14]:
#  one hot encoding

In [15]:
df = pd.get_dummies(df)

In [16]:
df

      User ID   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510  19.0          19000.0          0          False         True
1    15810944  35.0          20000.0          0          False         True
2    15668575  26.0          43000.0          0           True        False
3    15603246  27.0          57000.0          0           True        False
4    15804002  19.0          76000.0          0          False         True
..        ...   ...              ...        ...            ...          ...
395  15691863  46.0          41000.0          1           True        False
396  15706071  51.0          23000.0          1          False         True
397  15654296  50.0          20000.0          1           True        False
398  15755018  36.0          33000.0          0          False         True
399  15594041  49.0          36000.0          1           True        False

[400 rows x 6 columns]

In [17]:
import seaborn as sns

In [18]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [19]:
import seaborn as sns
df = sns.load_dataset('taxis');
df;